Repository KhronosGroup/glTF-Blender-IO, pull requests merged in 2019-01, with the labels that each got.

#195 Ignore non-deforming vertex weights when exporting from Blender
  addons/io_scene_gltf2/blender/exp/gltf2_blender_extract.py
Labels: exporter

#248 Feature: sort json by relevance
  addons/io_scene_gltf2/blender/exp/gltf2_blender_export.py
  addons/io_scene_gltf2/io/exp/gltf2_io_export.py
Labels: enhancement, exporter

#245 check vertices if they are attached to a vertex group before adding s…
  addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_nodes.py
Labels: exporter

#229 Importer: Manage KHR_materials_unlit
  addons/io_scene_gltf2/blender/imp/gltf2_blender_KHR_materials_unlit.py
  addons/io_scene_gltf2/blender/imp/gltf2_blender_material.py
  addons/io_scene_gltf2/blender/imp/gltf2_blender_pbrMetallicRoughness.py
  addons/io_scene_gltf2/io/imp/gltf2_io_gltf.py
Labels: enhancement, importer

#253 Much faster animation import
  addons/io_scene_gltf2/__init__.py
  addons/io_scene_gltf2/blender/imp/gltf2_blender_animation_bone.py
  addons/io_scene_gltf2/blender/imp/gltf2_blender_animation_node.py
Labels: enhancement, importer

#242 Fixed exporting non-number array custom properties
  addons/io_scene_gltf2/blender/exp/gltf2_blender_generate_extras.py
Labels: enhancement, exporter

#255 Reconnect the double-sided flag from the old custom node system.
  addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_materials.py
Labels: exporter
