Repository KhronosGroup/glTF-Blender-IO, pull requests merged in 2019-02, with the labels that each got.

#275 Make FCurve group names consistent with Blender
  addons/io_scene_gltf2/blender/imp/gltf2_blender_animation_bone.py
  addons/io_scene_gltf2/blender/imp/gltf2_blender_animation_node.py
Labels: enhancement, importer

#273 Fix exceptions on exporting lights.
  addons/io_scene_gltf2/blender/exp/gltf2_blender_extract.py
  addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_lights.py
  addons/io_scene_gltf2/blender/exp/gltf2_blender_search_node_tree.py
  addons/io_scene_gltf2/blender/imp/gltf2_blender_map_emissive.py
Labels: exporter

#288 accessibility through search bar
  addons/io_scene_gltf2/__init__.py
Labels: exporter, importer

#281 Disable armature modifier when applying modifiers and exporting skins
  addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_nodes.py
Labels: exporter

#292 Importer: add documentation for tool-tip popup
  addons/io_scene_gltf2/__init__.py
Labels: importer

#291 Exporter: correctly convert UV texture transforms
  addons/io_scene_gltf2/blender/com/gltf2_blender_conversion.py
  addons/io_scene_gltf2/blender/exp/gltf2_blender_get.py
Labels: exporter

#283 Auto limit and normalize skin weights
  addons/io_scene_gltf2/blender/exp/gltf2_blender_extract.py
  addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_primitive_attributes.py
Labels: exporter

#305 Feature: export at frame 0
  addons/io_scene_gltf2/__init__.py
  addons/io_scene_gltf2/blender/exp/gltf2_blender_export.py
  addons/io_scene_gltf2/blender/exp/gltf2_blender_export_keys.py
  docs/blender_docs/io_gltf2.rst
Labels: exporter

#306 added whitelist for empty collections
  addons/io_scene_gltf2/blender/exp/gltf2_blender_export.py
Labels: exporter

#280 Use mesh object's xfrom for inv bind matrix
  addons/io_scene_gltf2/blender/exp/gltf2_blender_extract.py
  addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_nodes.py
  addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_skins.py
Labels: exporter

#299 Fix texture transform conversion
  addons/io_scene_gltf2/blender/com/gltf2_blender_conversion.py
  addons/io_scene_gltf2/blender/exp/gltf2_blender_get.py
Labels: exporter

#295 Add more documentation on how materials get exported.
  .gitattributes
  README.md
  docs/README.md
  docs/blender_docs/io_gltf2.rst
  images/addons_io-gltf2-material-mapping.png
  images/addons_io-gltf2-material-metalRough.png
  images/addons_io-gltf2-material-normal.png
  images/addons_io-gltf2-material-principled.png
  images/addons_io-gltf2-material-unlit.png
  tools/copy_doc.py
Labels: documentation
