Repository KhronosGroup/glTF-Blender-IO, pull requests merged in 2019-10, with the labels that each got.

#706 Export with Always Sample Animations by default
  addons/io_scene_gltf2/__init__.py
  tests/roundtrip/01_morphed_cube/01_morphed_cube_options.txt
  tests/roundtrip_gltf.py
  tests/test/test.js
Labels: Animation, enhancement, exporter

#714 Fix #441 import multiple files
  addons/io_scene_gltf2/__init__.py
Labels: enhancement, exporter

#713 Export def bones
  addons/io_scene_gltf2/__init__.py
  addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_animation_channel_target.py
  addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_animation_channels.py
  addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_joints.py
  addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_nodes.py
  addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_skins.py
Labels: Skinning_&_Rigging, enhancement, exporter

#709 Import extra data as custom properties
  addons/io_scene_gltf2/blender/com/gltf2_blender_extras.py
  addons/io_scene_gltf2/blender/exp/gltf2_blender_gather.py
  addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_cameras.py
  addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_lights.py
  addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_materials.py
  addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_mesh.py
  addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_nodes.py
  addons/io_scene_gltf2/blender/imp/gltf2_blender_camera.py
  addons/io_scene_gltf2/blender/imp/gltf2_blender_light.py
  addons/io_scene_gltf2/blender/imp/gltf2_blender_material.py
  addons/io_scene_gltf2/blender/imp/gltf2_blender_mesh.py
  addons/io_scene_gltf2/blender/imp/gltf2_blender_node.py
Labels: enhancement, exporter, importer

#741 Export: fix #737
  addons/io_scene_gltf2/blender/exp/gltf2_blender_extract.py
Labels: bug, exporter

#753 Fix #752 fix euler complete keyframe issue
  addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_animation_sampler_keyframes.py
Labels: Animation, bug, exporter

#755 Export: fix #754
  addons/io_scene_gltf2/blender/exp/gltf2_blender_extract.py
Labels: Mesh_&_Object, enhancement, exporter

#742 Import: fixes around buffers and GLB-handling
  addons/io_scene_gltf2/io/imp/gltf2_io_binary.py
  addons/io_scene_gltf2/io/imp/gltf2_io_gltf.py
Labels: enhancement, importer
