Repository KhronosGroup/glTF-Blender-IO, pull requests merged in 2020-09, with the labels that each got.

#1120 Export/Perf: use numpy in extract_primitives (2-8x speedup)
  addons/io_scene_gltf2/blender/exp/gltf2_blender_extract.py
  addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_nodes.py
  addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_primitive_attributes.py
  addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_primitives.py
Labels: Mesh_&_Object, enhancement, exporter

#1136 Import/Perf: for "Use Normal Data", numpyify the code that guesses which polys are flat
  addons/io_scene_gltf2/blender/imp/gltf2_blender_mesh.py
Labels: Mesh_&_Object, enhancement, importer

#1157 Export: always write texture samplers
  addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_sampler.py
Labels: Material, enhancement, exporter

#1162 Import: select all (and only) the imported objects
  addons/io_scene_gltf2/blender/imp/gltf2_blender_scene.py
Labels: enhancement, importer

#1177 Import: use action_group parameter to fcurves.new
  addons/io_scene_gltf2/blender/imp/gltf2_blender_animation_utils.py
Labels: Animation, enhancement, importer

#1146 Update gltf2_blender_gltf2_exporter.py to allow for extensions in the asset node
  addons/io_scene_gltf2/blender/exp/gltf2_blender_gltf2_exporter.py
  example-addons/example_gltf_extension/readme.md
Labels: addon, enhancement, exporter

#1155 Export: materials: export factors from MULTIPLY nodes
  addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_materials.py
  addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_materials_pbr_metallic_roughness.py
  addons/io_scene_gltf2/blender/exp/gltf2_blender_get.py
  tests/roundtrip/11_factors_and_textures/11_factors_and_textures.bin
  tests/roundtrip/11_factors_and_textures/11_factors_and_textures.gltf
  tests/roundtrip/11_factors_and_textures/Blank.png
  tests/test/test.js
Labels: Material, enhancement, exporter

#1167 Import/Perf: ensure normalized accessors decode to float32s
  addons/io_scene_gltf2/io/imp/gltf2_io_binary.py
Labels: enhancement, importer

#1169 Export: store vertex colors as normalized ushorts
  addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_primitive_attributes.py
Labels: Material, enhancement, exporter

#1147 Refactor: delete fmt_char_dict/component_nb_dict
  addons/io_scene_gltf2/io/imp/gltf2_io_binary.py
  addons/io_scene_gltf2/io/imp/gltf2_io_gltf.py
Labels: enhancement, importer

#1165 Import: convert glTF meters to the units of the Blender scene
  addons/io_scene_gltf2/blender/imp/gltf2_blender_gltf.py
  addons/io_scene_gltf2/blender/imp/gltf2_blender_mesh.py
Labels: enhancement, importer

#1170 Export: detect when a file will be overwritten (#718)
  addons/io_scene_gltf2/__init__.py
Labels: enhancement, exporter

#1114 Ignore Muted Material Nodes
  addons/io_scene_gltf2/blender/exp/gltf2_blender_get.py
Labels: Material, enhancement, exporter

#1148 Export: support use_nodes=False materials
  addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_materials_pbr_metallic_roughness.py
Labels: Material, enhancement, exporter

#1159 Export: materials: support emission strength
  addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_materials.py
  addons/io_scene_gltf2/blender/exp/gltf2_blender_get.py
Labels: Material, enhancement, exporter
