Repository KhronosGroup/glTF-Blender-IO, pull requests merged in 2020-03, with the labels that each got.

#946 Import: prettify bones
  addons/io_scene_gltf2/__init__.py
  addons/io_scene_gltf2/blender/com/gltf2_blender_math.py
  addons/io_scene_gltf2/blender/imp/gltf2_blender_animation_bone.py
  addons/io_scene_gltf2/blender/imp/gltf2_blender_animation_node.py
  addons/io_scene_gltf2/blender/imp/gltf2_blender_node.py
  addons/io_scene_gltf2/blender/imp/gltf2_blender_vnode.py
Labels: Skinning_&_Rigging, enhancement, importer

#922 glTF2: Speed up imports with vertex colors using numpy
  addons/io_scene_gltf2/blender/imp/gltf2_blender_gltf.py
  addons/io_scene_gltf2/blender/imp/gltf2_blender_primitive.py
  addons/io_scene_gltf2/io/com/gltf2_io_color_management.py
Labels: enhancement, importer

#919 Enable a gltf_gltf2_hook
  addons/io_scene_gltf2/blender/exp/gltf2_blender_export.py
  addons/io_scene_gltf2/io/exp/gltf2_io_user_extensions.py
Labels: enhancement, exporter

#941 Import: guess original bind pose from inverseBindMatrices
  addons/io_scene_gltf2/__init__.py
  addons/io_scene_gltf2/blender/imp/gltf2_blender_vnode.py
Labels: Skinning_&_Rigging, enhancement, importer
