Repository KhronosGroup/glTF-Blender-IO, pull requests merged in 2020-01, with the labels that each got.

#812 Export: use Compositor to build images instead of pixel pushing (~4x faster at packing big metal/rough/occlusion textures)
  addons/io_scene_gltf2/blender/exp/gltf2_blender_image.py
Labels: Material, exporter

#849 Convert user extensions to dictionaries
  addons/io_scene_gltf2/io/com/gltf2_io.py
Labels: exporter

#883 Export: implement image options change (#882)
  addons/io_scene_gltf2/__init__.py
  addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_image.py
  addons/io_scene_gltf2/blender/exp/gltf2_blender_image.py
Labels: Material, enhancement, exporter

#867 Import/Perf: speed up animation keyframe creation
  addons/io_scene_gltf2/blender/imp/gltf2_blender_animation_utils.py
Labels: Animation, importer

#857 Import: fix skinning (and other node hierarchy problems)
  addons/io_scene_gltf2/blender/com/gltf2_blender_conversion.py
  addons/io_scene_gltf2/blender/imp/gltf2_blender_animation.py
  addons/io_scene_gltf2/blender/imp/gltf2_blender_animation_bone.py
  addons/io_scene_gltf2/blender/imp/gltf2_blender_animation_node.py
  addons/io_scene_gltf2/blender/imp/gltf2_blender_animation_weight.py
  addons/io_scene_gltf2/blender/imp/gltf2_blender_camera.py
  addons/io_scene_gltf2/blender/imp/gltf2_blender_gltf.py
  addons/io_scene_gltf2/blender/imp/gltf2_blender_light.py
  addons/io_scene_gltf2/blender/imp/gltf2_blender_mesh.py
  addons/io_scene_gltf2/blender/imp/gltf2_blender_node.py
  addons/io_scene_gltf2/blender/imp/gltf2_blender_primitive.py
  addons/io_scene_gltf2/blender/imp/gltf2_blender_scene.py
  addons/io_scene_gltf2/blender/imp/gltf2_blender_skin.py
  addons/io_scene_gltf2/blender/imp/gltf2_blender_vnode.py
  addons/io_scene_gltf2/io/com/gltf2_io_trs.py
  addons/io_scene_gltf2/io/imp/gltf2_io_gltf.py
Labels: importer

#824 Camera import fixes
  addons/io_scene_gltf2/blender/imp/gltf2_blender_camera.py
Labels: importer

#841 Import: simplify/cleanup image import
  addons/io_scene_gltf2/blender/imp/gltf2_blender_image.py
Labels: importer

#831 Import: rewrite material code
  addons/io_scene_gltf2/blender/com/gltf2_blender_material_helpers.py
  addons/io_scene_gltf2/blender/imp/gltf2_blender_KHR_materials_pbrSpecularGlossiness.py
  addons/io_scene_gltf2/blender/imp/gltf2_blender_KHR_materials_unlit.py
  addons/io_scene_gltf2/blender/imp/gltf2_blender_gltf.py
  addons/io_scene_gltf2/blender/imp/gltf2_blender_map_emissive.py
  addons/io_scene_gltf2/blender/imp/gltf2_blender_map_normal.py
  addons/io_scene_gltf2/blender/imp/gltf2_blender_map_occlusion.py
  addons/io_scene_gltf2/blender/imp/gltf2_blender_material.py
  addons/io_scene_gltf2/blender/imp/gltf2_blender_pbrMetallicRoughness.py
  addons/io_scene_gltf2/blender/imp/gltf2_blender_texture.py
  addons/io_scene_gltf2/io/imp/gltf2_io_gltf.py
Labels: Material, enhancement, importer
