Repository KhronosGroup/glTF-Blender-IO, pull requests merged in 2020-04, with the labels that each got.

#1011 Import: improve node names
  addons/io_scene_gltf2/blender/imp/gltf2_blender_node.py
  addons/io_scene_gltf2/blender/imp/gltf2_blender_vnode.py
Labels: importer

#1003 Import: set camera near/far (fix #1002)
  addons/io_scene_gltf2/blender/imp/gltf2_blender_camera.py
Labels: importer

#998 Export: less naive file format detection (fix #986)
  addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_image.py
  addons/io_scene_gltf2/blender/exp/gltf2_blender_image.py
Labels: exporter

#997 Import/Refactor: simplify animation code
  addons/io_scene_gltf2/blender/imp/gltf2_blender_animation.py
  addons/io_scene_gltf2/blender/imp/gltf2_blender_animation_bone.py
  addons/io_scene_gltf2/blender/imp/gltf2_blender_animation_node.py
  addons/io_scene_gltf2/blender/imp/gltf2_blender_animation_utils.py
  addons/io_scene_gltf2/blender/imp/gltf2_blender_animation_weight.py
  addons/io_scene_gltf2/blender/imp/gltf2_blender_scene.py
Labels: importer

#1018 Export/Perf: use foreach_{get,set} for image encoding
  addons/io_scene_gltf2/__init__.py
  addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_primitives.py
  addons/io_scene_gltf2/blender/exp/gltf2_blender_image.py
Labels: Material, enhancement, exporter

#1034 Perf: revert #922
  addons/io_scene_gltf2/blender/imp/gltf2_blender_primitive.py
  addons/io_scene_gltf2/io/com/gltf2_io_color_management.py
Labels: Material, importer

#1035 Change the way sampled keyframe types are determined.
  addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_animation_samplers.py
Labels: Animation, exporter

#1029 Export: joint extras
  addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_joints.py
Labels: enhancement, exporter

#1022 Dont fail when using custom property animations
  addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_animation_channel_target.py
  addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_animation_channels.py
Labels: Animation, enhancement, exporter

#1028 Import: use friendly filenames for temp image files (fix #1026)
  addons/io_scene_gltf2/blender/imp/gltf2_blender_image.py
  addons/io_scene_gltf2/io/imp/gltf2_io_binary.py
  addons/io_scene_gltf2/io/imp/gltf2_io_gltf.py
Labels: Material, enhancement, importer

#1025 Export: don't combine image names if they're all from the same file (fix #1014)
  addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_image.py
Labels: Material, enhancement, exporter

#1016 Docs: add basic documentation for the two new import options
  docs/blender_docs/io_scene_gltf2.rst
Labels: documentation
